[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#FF4B4B"

[server]
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
enableStaticServing = false
runOnSave = true

[logger]
level = "error" 